# Generated by Django 4.2.1 on 2023-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('done', models.CharField(choices=[('d', 'Сделанно'), ('n', 'Не сделанно')], default='n', max_length=1)),
            ],
        ),
    ]
