# Generated by Django 4.2.1 on 2023-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts',
            name='description',
            field=models.TextField(),
        ),
    ]
