# Generated by Django 4.2.1 on 2023-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_ts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
